### PR TITLE
Use VirtualAlloc for rom and ram buffers

### PR DESCRIPTION
**Pull request by aglab2**

### CODE REVIEW

**Comment by Aurumaker72** [comment]
Hi, thank you for the contribution.

This change looks good and shouldn't affect anything negatively, as the same block address is given out every time.

I'm curious about the rationale for this change: is it required for a graphics plugin, or is it something else?

**Comment by aglab2** [comment]
Hi, this is necessary for [StarDisplay tool](https://github.com/aglab2/SM64StarDisplay). It scans regions of VirtualAlloc to find where ROM and RAM is.

**Comment by Aurumaker72** [comment]
Changing malloc or static allocations to VirtualAlloc is not required in order to find the RAM start externally.

See [Frame's STROOP](https://github.com/FramePerfection/STROOP/blob/Development/STROOP/Utilities/Stream/WindowsProcessIO.cs#L97) as a reference for performing this pattern detection.

**Comment by aglab2** [comment]
STROOP approach will only work for US and JP versions of base game. Decomp romhack will fail that check or, if laxed similar to MagicManager [first 4 byte check with mask](https://github.com/aglab2/SM64StarDisplay/blob/master/StarManager/Managers/MagicManager.cs#L15-L17), will cause false positives. Having memory in a dedicated VirtualAlloc buffer is much cleaner plus it allows to move buffer past 0x80000000 on x86 with appropriate manifest to reduce runtime memory costs.

**Comment by Aurumaker72** [comment]
It seems as if that's more of an issue with STROOP's limited heuristic, and not the allocation method. Additionally, I don't see how an explicit WinAPI allocation call is inherently cleaner and why the buffer would need to move past 0x80000000.

Despite that, this doesn't seem to have any downsides, so it's ripe for merging 👍

**Review by Aurumaker72 — APPROVED** [review]

**Comment by Aurumaker72** [comment]
My bad, this change adds a Windows dependency to the OS-agnostic emulation core.

It will be reverted as it is not justifiable. The ramstart detection heuristics of StarDisplay must improve and Mupen64 shouldn't need to bend its code around an external tool.

**Comment by Aurumaker72** [comment]
The segmentation doesn't seem to be needed, so it's fine to just align to 4k block?

```
__declspec(align(4 * 1024))
unsigned long rdram[0x800000 / 4];
```

I wonder why this is required - Mupen is x86-only, so is this just something that's inherently required by Parallel?

**Comment by aglab2** [comment]
Yes, it is a requirement for parallel. It is mapping rdram from CPU to GPU using [external_host_memory](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_external_memory_host.html). I am no GPU expert but I can only assume that at least page alignment is needed for tricks like that.

**Comment by aglab2** [comment]
Another solution I could propose is using `mmap` - there is a crossplatform header for Windows support, it will work outside of Windows too. If it will be acceptable for mupen, I can add a PR for that.

**Comment by Aurumaker72** [comment]
We need it three times, twice for a malloc, and once for a free all in one file. A conditional macro pointing to `_aligned_malloc` and `std::aligned_alloc` should be enough.

Trying with the specified RDRAM band guards and alignment, along with ROM alignment while using [pj64-parallelrdp](https://github.com/Rosalie241/pj64-parallelrdp/releases) displays garbled graphics.

**Pull request merged**
