### PR TITLE
Added wgui.clearimage and wgui.drawimagescale

### PR DESCRIPTION
**Pull request by Wade7wastaken**
Documentation:
`nil wgui.clearimage(int clearIndex)`
Clears an image from imagePool at location clearIndex. If clearIndex is 0, all images in imagePool are deleted.
`nil wgui.drawimagescale(int imgIndex, int left, int top, number xscale, number yscale)`
Identical to wgui.drawimage, but with scaling.

### CODE REVIEW

**Comment by Aurumaker72** [comment]
I suggest renaming `wgui.clearimage` to `wgui.deleteimage`, as the former doesn't imply a deletion from image pool but rather a reset of an image.

**Comment by Wade7wastaken** [comment]
Yeah, that makes sense

**Comment by Wade7wastaken** [comment]
Is there a way to edit the commit after I've created the pull request?

**Comment by Aurumaker72** [comment]
Yes, you can push an additional commit to your fork

**Comment by Wade7wastaken** [comment]
Ok, changed

**Comment by Aurumaker72** [comment]
LGTM

**Pull request merged**
